"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { authorizedClient } from "@/lib/permissions";
import { checkDatabase, publicError } from "@/lib/errors";

const employeeSchema=z.object({first_name:z.string().trim().min(1).max(120),last_name:z.string().trim().min(1).max(120),employee_code:z.string().trim().max(80).default(""),legal_entity_id:z.union([z.uuid(),z.literal("")]).transform(v=>v||null),country:z.string().trim().max(80).default(""),tax_identifier:z.string().trim().max(100).default(""),birth_date:z.union([z.iso.date(),z.literal("")]).default(""),birth_place:z.string().trim().max(160).default(""),nationality:z.string().trim().max(80).default(""),hire_date:z.union([z.iso.date(),z.literal("")]).default(""),termination_date:z.union([z.iso.date(),z.literal("")]).default(""),role_title:z.string().trim().max(160).default(""),employment_level:z.string().trim().max(100).default(""),contract_type:z.string().trim().max(100).default(""),status:z.enum(["to_hire","active","suspended","terminated","archived"]),email:z.string().trim().email().or(z.literal("")),phone:z.string().trim().max(80).default(""),notes:z.string().max(10000).default("")});
function payload(form:FormData){return employeeSchema.parse(Object.fromEntries(form));}
async function mutate(path:string,message:string,work:()=>Promise<string|void>){let id:string|void;try{id=await work();}catch(e){const x=publicError(e);redirect(`${path}?error=${encodeURIComponent(x.message)}&error_kind=${x.kind}`);}revalidatePath("/personale","layout");revalidatePath("/scadenze","layout");redirect(`${id?`/personale/${id}`:path}?success=${encodeURIComponent(message)}`);}
export async function saveEmployeeAction(form:FormData){const id=String(form.get("id")||"");return mutate(id?`/personale/${id}`:"/personale","Dipendente salvato.",async()=>{const db=await authorizedClient(id?"employee.update":"employee.create");const data=payload(form);const r=id?await db.from("employees").update(data).eq("id",id).is("archived_at",null).select("id").single():await db.from("employees").insert(data).select("id").single();checkDatabase(r.error,"Salvataggio dipendente");if(!r.data) throw new Error("Salvataggio non confermato.");return String(r.data.id);});}
export async function archiveEmployeeAction(form:FormData){const id=String(form.get("id")||"");return mutate("/personale","Dipendente archiviato.",async()=>{const db=await authorizedClient("employee.archive");const r=await db.rpc("archive_employee",{employee_id:id,archived:true});checkDatabase(r.error,"Archiviazione dipendente");});}
export async function restoreEmployeeAction(form:FormData){const id=String(form.get("id")||"");return mutate(`/personale/${id}`,"Dipendente ripristinato.",async()=>{const db=await authorizedClient("employee.archive");const r=await db.rpc("archive_employee",{employee_id:id,archived:false});checkDatabase(r.error,"Ripristino dipendente");});}
