import { authorizedClient } from "@/lib/permissions";
import { checkDatabase } from "@/lib/errors";

export async function getOffers(params:{q?:string;status?:string;page?:number}={}) {
 const db=await authorizedClient("offer.read"); let q=db.from("offers").select("*, companies(business_name), legal_entities(code)",{count:"exact"}).eq("is_current",true).is("archived_at",null);
 if(params.q) q=q.or(`offer_number.ilike.%${params.q}%,subject.ilike.%${params.q}%`); if(params.status) q=q.eq("status",params.status);
 const page=Math.max(1,params.page??1); const r=await q.order("issued_at",{ascending:false}).range((page-1)*50,page*50-1); checkDatabase(r.error,"Offerte"); return {rows:r.data??[],count:r.count??0};
}
export async function getOffer(id:string){const db=await authorizedClient("offer.read");const [o,l,p,orders,docs]=await Promise.all([db.from("offers").select("*, companies(business_name), legal_entities(code)").eq("id",id).maybeSingle(),db.from("offer_lines").select("*").eq("offer_id",id).order("position"),db.from("offer_projects").select("project_id, projects(project_code,name)").eq("offer_id",id),db.from("offer_orders").select("order_id, orders(order_number,order_date)").eq("offer_id",id),db.from("document_offers").select("document_id, documents(id,title,original_filename)").eq("offer_id",id)]);[o,l,p,orders,docs].forEach(x=>checkDatabase(x.error));return {offer:o.data,lines:l.data??[],projects:p.data??[],orders:orders.data??[],documents:docs.data??[]};}
export async function getContracts(params:{q?:string;status?:string;page?:number}={}) {const db=await authorizedClient("contract.read");let q=db.from("contracts").select("*, companies(business_name), legal_entities(code)",{count:"exact"}).is("archived_at",null);if(params.q)q=q.or(`reference.ilike.%${params.q}%,title.ilike.%${params.q}%`);if(params.status)q=q.eq("status",params.status);const page=Math.max(1,params.page??1);const r=await q.order("starts_at",{ascending:false}).range((page-1)*50,page*50-1);checkDatabase(r.error,"Contratti");return {rows:r.data??[],count:r.count??0};}
export async function getContract(id:string){const db=await authorizedClient("contract.read");const [c,p,o,i,d,dead]=await Promise.all([db.from("contracts").select("*, companies(business_name), legal_entities(code)").eq("id",id).maybeSingle(),db.from("contract_projects").select("project_id, projects(project_code,name)").eq("contract_id",id),db.from("contract_orders").select("order_id, orders(order_number,order_date)").eq("contract_id",id),db.from("contract_invoices").select("invoice_id, invoices(invoice_number,invoice_date,amount_total,currency)").eq("contract_id",id),db.from("document_contracts").select("document_id, documents(id,title,original_filename)").eq("contract_id",id),db.from("deadlines").select("id,title,due_date,status").eq("contract_id",id)]);[c,p,o,i,d,dead].forEach(x=>checkDatabase(x.error));return {contract:c.data,projects:p.data??[],orders:o.data??[],invoices:i.data??[],documents:d.data??[],deadlines:dead.data??[]};}
