# Local Supabase config
# If you want to link this repo locally, run:
# supabase link --project-ref <your-project-ref>

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
shadow_port = 54320
[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
file_size_limit = "50MiB"
