import { formatDate, formatMoney } from "@/lib/formatters";
import Link from "@/components/ui/app-link";
import { authorizedClient,requirePagePermission } from "@/lib/permissions";
import { hasPermission } from "@/lib/auth";
import { checkDatabase } from "@/lib/errors";
import { readAll } from "@/lib/data";
import { commercialRelationAction } from "@/lib/commercial-actions";
import { SubmitButton } from "@/components/ui/submit-button";
import type { CommercialRecord } from "@/lib/commercial";
import type { CommercialKind } from "@/lib/commercial-validation";
export async function InvoiceLinks({kind,record}:{kind:CommercialKind;record:CommercialRecord}){
 const user=await requirePagePermission(`${kind}.read`);if(!hasPermission(user.role,"invoice.read"))return null;
 const db=await authorizedClient("invoice.read"),key=kind==="order"?"order_id":"delivery_note_id";
 const result=await db.from(kind==="order"?"order_invoices":"delivery_note_invoices").select("*").eq(key,record.id);checkDatabase(result.error);
 const ids=(result.data??[]).map(x=>String(x.invoice_id));
 const linked=ids.length?await db.from("invoices").select("id,invoice_number,invoice_date,currency,amount_total,archived_at").in("id",ids):{data:[],error:null};checkDatabase(linked.error);
 const write=hasPermission(user.role,`${kind}.update`)&&!record.archived_at;
 const type=kind==="order"?record.order_type:record.direction==="inbound"?"purchase":"sale";
 const choices=write&&record.counterparty_id?await readAll((a,b)=>{let q=db.from("invoices").select("id,invoice_number,invoice_date,currency,amount_total").eq("legal_entity_id",record.legal_entity_id).eq("invoice_type",type).eq(type==="purchase"?"supplier_id":"customer_id",record.counterparty_id).is("archived_at",null);if(kind==="order")q=q.eq("currency",record.currency);return q.order("invoice_date",{ascending:false}).order("id").range(a,b);}):[];
 const fields=<><input type="hidden" name="kind" value={kind}/><input type="hidden" name="record_id" value={record.id}/></>;
 const invoiceLines=ids.length?await readAll((a,b)=>db.from("invoice_lines").select("id,invoice_id,description,quantity,unit,project_id").in("invoice_id",ids).order("id").range(a,b)):[];
 const alloc=record.lines.length?await db.from("commercial_invoice_lines").select("*").in(kind==="order"?"order_line_id":"delivery_note_line_id",record.lines.map(l=>l.id!)):{data:[],error:null};checkDatabase(alloc.error);
 return <section className="app-card p-3 my-3"><h2 className="h5">Fatture collegate</h2>
 <div className="table-responsive"><table className="table table-sm"><thead><tr><th>Fattura</th><th>Data</th><th>Valuta</th><th>Totale documento</th>{kind==="order"&&<th>Importo attribuito</th>}<th>Azioni</th></tr></thead><tbody>{(linked.data??[]).map(i=><tr key={i.id}><td><Link href={`/fatture/${i.id}`}>{i.invoice_number}</Link>{i.archived_at&&" (archiviata)"}</td><td>{formatDate(i.invoice_date)}</td><td>{i.currency}</td><td>{formatMoney(i.amount_total,i.currency)}</td>{kind==="order"&&<td>{result.data?.find(x=>x.invoice_id===i.id)?.allocated_amount==null?"Da attribuire":formatMoney(result.data?.find(x=>x.invoice_id===i.id)?.allocated_amount,i.currency)}</td>}<td>{write&&!i.archived_at&&<form action={commercialRelationAction}>{fields}<input type="hidden" name="invoice_id" value={i.id}/><input type="hidden" name="operation" value="unlink"/><SubmitButton className="btn btn-outline-secondary btn-sm">Scollega</SubmitButton></form>}</td></tr>)}</tbody></table></div>
 {!ids.length&&<p className="text-muted">Nessuna fattura collegata. Il flusso può non prevedere una fattura.</p>}
 {write&&<form action={commercialRelationAction} className="row g-2">{fields}<div className="col-md-7"><label htmlFor="invoice-link" className="form-label">Fattura compatibile</label><select id="invoice-link" name="invoice_id" className="form-select" required><option value="">Seleziona fattura</option>{choices.map(i=><option key={i.id} value={i.id}>{i.invoice_number} · {formatDate(i.invoice_date)} · {formatMoney(i.amount_total,i.currency)}</option>)}</select></div>{kind==="order"&&<div className="col-md-3"><label htmlFor="allocation-amount" className="form-label">Importo attribuito ({record.currency})</label><input id="allocation-amount" name="amount" type="number" step="0.01" min="0" className="form-control"/><small>Vuoto = importo non determinabile. Puoi aggiornare un collegamento esistente.</small></div>}<div className="col-md-2 align-self-center"><SubmitButton className="btn btn-outline-primary">Collega fattura</SubmitButton></div></form>}
 <h3 className="h6 mt-4">Quantità fatturate per riga</h3>
 {(alloc.data??[]).map(a=>{const il=invoiceLines.find(l=>l.id===a.invoice_line_id);return <div key={a.id} className="d-flex gap-2 align-items-center border-bottom py-2"><span>{record.lines.find(l=>l.id===(kind==="order"?a.order_line_id:a.delivery_note_line_id))?.description} → {il?.description??"Riga fattura"}: {a.quantity}</span>{write&&hasPermission(user.role,"invoice.update")&&<form action={commercialRelationAction}>{fields}<input type="hidden" name="operation" value="unlink_line"/><input type="hidden" name="allocation_id" value={a.id}/><SubmitButton className="btn btn-sm btn-outline-secondary">Rimuovi attribuzione</SubmitButton></form>}</div>;})}
 {!(alloc.data??[]).length&&<p className="small text-muted">Quantità fatturate non attribuite. Il collegamento alla sola intestazione non determina le quantità.</p>}
 {write&&invoiceLines.length>0&&<form action={commercialRelationAction} className="row g-2 mt-2">{fields}<input type="hidden" name="operation" value="line"/><div className="col-md-4"><label className="form-label" htmlFor="commercial-line">Riga {kind==="order"?"ordine":"DDT"}</label><select id="commercial-line" name={kind==="order"?"order_line_id":"delivery_note_line_id"} className="form-select" required>{record.lines.map(l=><option key={l.id} value={l.id}>{l.description} · {l.quantity} {l.unit}</option>)}</select></div><div className="col-md-4"><label className="form-label" htmlFor="invoice-line">Riga fattura (stessa commessa e unità)</label><select id="invoice-line" name="invoice_line_id" className="form-select" required>{invoiceLines.map(l=><option key={l.id} value={l.id}>{linked.data?.find(i=>i.id===l.invoice_id)?.invoice_number} · {l.description} · {l.quantity} {l.unit}</option>)}</select></div><div className="col-md-2"><label className="form-label" htmlFor="invoice-line-quantity">Quantità</label><input id="invoice-line-quantity" name="quantity" type="number" step="0.001" min="0.001" required className="form-control"/></div><div className="col-md-2 align-self-end"><SubmitButton className="btn btn-outline-primary">Attribuisci quantità</SubmitButton></div></form>}
 </section>;
}
