import { InvoiceProjectRequirement } from "@/components/work/invoice-requirement";
import { ContextWork, ContextAnomalies } from "@/components/work/context";
import { FileLink } from "@/components/documents/file-link";
import { formatDate, formatMoney } from "@/lib/formatters";
import { InvoiceCycle } from "@/components/commercial/invoice-cycle";
import { SubmitButton } from "@/components/ui/submit-button";
import { getArchiveDocument } from "@/lib/documents";
import Link from "@/components/ui/app-link";
import { notFound } from "next/navigation";
import { requirePagePermission, getAccessScope } from "@/lib/permissions";
import { getInvoiceById } from "@/lib/data";
import { ActivityTimeline } from "@/components/ui/activity-timeline";
import { getInvoiceFinancialSummaries, getInstallmentBalances } from "@/lib/finance";
import { saveFinancialMovementAction } from "@/lib/crud";
import { StatusBadge } from "@/components/ui/status-badge";
import { UploadDocumentTrigger } from "@/components/documents/upload-document-trigger";
import { PdfPreviewModal } from "@/components/documents/pdf-preview-modal";
export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePagePermission("invoice.read");
  const invoice = await getInvoiceById((await params).id); if (!invoice) notFound();
  const pdf=invoice.document_id?await getArchiveDocument(invoice.document_id):null;
  const installmentBalances=await getInstallmentBalances(invoice.id);
  const access = await getAccessScope("invoice");
  const financial = (await getInvoiceFinancialSummaries([invoice.id])).get(invoice.id) ?? { paid: 0, residual: invoice.amount_total, financialStatus: "to_pay" as const };
  const money = (value: number) => formatMoney(value,invoice.currency);
  return <><div className="d-flex justify-content-between mb-4"><h1 className="h3">Fattura {invoice.invoice_number}</h1><StatusBadge domain="invoice" status={invoice.status}/>{access.canUpdate && <Link className="btn btn-dark" href={`/fatture/${invoice.id}/edit`}>Modifica</Link>}</div>
    <div className="app-card p-3 mb-3"><dl className="row"><dt className="col-sm-3">Progressivo eSolver</dt><dd className="col-sm-9">{invoice.esolver_registration_number || "—"}</dd><dt className="col-sm-3">Società</dt><dd className="col-sm-9">{invoice.company_name}</dd><dt className="col-sm-3">Controparte</dt><dd className="col-sm-9"><Link href={`/${invoice.invoice_type === "purchase" ? "fornitori" : "clienti"}/${invoice.supplier_id ?? invoice.customer_id}`}>{invoice.customer_name}</Link></dd>
    <dt className="col-sm-3">Commesse</dt><dd className="col-sm-9">{invoice.linked_projects.length ? invoice.linked_projects.map(p => <Link key={p.id} className="me-3" href={`/commesse/${p.id}`}>{p.project_code}</Link>) : "Nessuna commessa collegata"}</dd>
    <dt className="col-sm-3">Imponibile</dt><dd className="col-sm-9">{money(invoice.amount_net)}</dd><dt className="col-sm-3">IVA registrata</dt><dd className="col-sm-9">{money(invoice.vat_amount)}{invoice.vat_rate !== null ? ` (${invoice.vat_rate}%)` : ""}</dd><dt className="col-sm-3">Totale</dt><dd className="col-sm-9">{money(invoice.amount_total)}</dd><dt className="col-sm-3">Pagato / incassato</dt><dd className="col-sm-9">{money(financial.paid)}</dd><dt className="col-sm-3">Residuo</dt><dd className="col-sm-9">{money(financial.residual)} <StatusBadge domain="payment" status={financial.financialStatus}/></dd><dt className="col-sm-3">Scadenza</dt><dd className="col-sm-9">{invoice.due_date ?? "—"}</dd><dt className="col-sm-3">Note</dt><dd className="col-sm-9">{invoice.notes || "—"}</dd></dl>
    <section className="document-inline-panel mt-3" aria-labelledby="invoice-document-title"><h2 className="h6 mb-2" id="invoice-document-title"><i className="bi bi-file-earmark-pdf me-2 text-danger" aria-hidden="true"/>Documento fattura</h2>{pdf&&pdf.file_state==="ready"&&!pdf.archived_at?<div className="d-flex align-items-center gap-3 flex-wrap"><span className="text-truncate">{pdf.title||pdf.original_filename}</span><PdfPreviewModal versionId={pdf.current_version_id} filename={pdf.title||pdf.original_filename||"Fattura PDF"}/><FileLink className="btn btn-sm btn-outline-secondary" href={`/documenti/versioni/${pdf.current_version_id}/file?download=1`}><i className="bi bi-download me-1" aria-hidden="true"/>Scarica</FileLink></div>:<p className="text-muted mb-0">Nessun PDF allegato.</p>}{access.canUpdate&&<div className="mt-2"><UploadDocumentTrigger context={{invoice:invoice.id}}/></div>}</section></div>
    {access.canUpdate && financial.residual > 0 && <div className="app-card p-3 mb-3"><h2 className="h5">{invoice.invoice_type === "purchase" ? "Registra pagamento" : "Registra incasso"}</h2><form action={saveFinancialMovementAction} className="row g-2"><input type="hidden" name="direction" value={invoice.invoice_type === "purchase" ? "payment" : "receipt"}/><input type="hidden" name="legal_entity_id" value={invoice.legal_entity_id ?? ""}/><input type="hidden" name="counterparty_id" value={invoice.supplier_id ?? invoice.customer_id ?? ""}/><input type="hidden" name="currency" value={invoice.currency}/><input type="hidden" name="primary_invoice_id" value={invoice.id}/><div className="col-md-3"><label className="form-label">Importo</label><input name="amount" type="number" step="0.01" min="0.01" defaultValue={financial.residual.toFixed(2)} className="form-control" required/></div><div className="col-md-3"><label className="form-label">Data</label><input name="movement_date" type="date" defaultValue={new Date().toISOString().slice(0,10)} className="form-control" required/></div><div className="col-md-3"><label className="form-label">Metodo</label><input name="payment_method" className="form-control"/></div><div className="col-md-3"><label className="form-label">Riferimento</label><input name="reference" className="form-control"/></div><div className="col-12"><SubmitButton className="btn btn-primary" pendingLabel="Registrazione…">{invoice.invoice_type === "purchase" ? "Registra pagamento" : "Registra incasso"}</SubmitButton></div></form></div>}
    <div className="app-card p-3 mb-3"><h2 className="h5">Righe registrate</h2>{invoice.lines.length ? <div className="table-responsive"><table className="table"><thead><tr><th>Descrizione</th><th>Imponibile</th><th>Aliquota</th><th>IVA</th><th>Totale</th></tr></thead><tbody>{invoice.lines.map(l => <tr key={l.id}><td>{l.description}</td><td>{money(l.amount_net)}</td><td>{l.vat_exempt_reason || (l.vat_rate === null ? "—" : `${l.vat_rate}%`)}</td><td>{money(l.amount_vat)}</td><td>{money(l.amount_total)}</td></tr>)}</tbody></table></div> : <p>Nessuna riga registrata.</p>}</div>
    <div className="app-card p-3 mb-3"><h2 className="h5">Rate registrate</h2>{invoice.installments.length ? <ul>{invoice.installments.map(i => <li key={i.id} id={`rata-${i.id}`}>{formatDate(i.due_date)} — {money(i.amount)} — Saldato: {money(installmentBalances.get(i.id)?.paid??0)} — Residuo: {money(installmentBalances.get(i.id)?.residual??i.amount)}</li>)}</ul> : <p>Nessuna rata registrata.</p>}</div><InvoiceCycle id={invoice.id}/><ActivityTimeline items={[]} /><InvoiceProjectRequirement id={invoice.id} canUpdate={access.canUpdate}/><ContextAnomalies kind="invoice" id={invoice.id}/><ContextWork kind="invoice" id={invoice.id}/></>;
}
