import { SubmitButton } from "@/components/ui/submit-button";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getArchiveDocument,getDocumentVersions,getDocumentEvents,documentOptions } from "@/lib/documents";
import { requirePagePermission } from "@/lib/permissions";
import { hasPermission } from "@/lib/auth";
import { documentStatusLabels } from "@/lib/document-validation";
import { ContextFields } from "@/components/documents/document-fields";
import { deleteDocumentAction,restoreDocumentAction,linkDocumentAction,finalizeDocumentAction } from "@/lib/upload";
import { ConfirmSubmitButton } from "@/components/ui/confirm-submit-button";
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{success?:string}>}){
 const user=await requirePagePermission("document.read"),{id}=await params,doc=await getArchiveDocument(id);if(!doc)notFound();
 const [versions,events,o,p]=await Promise.all([getDocumentVersions(id),getDocumentEvents(id),documentOptions(),searchParams]);
 const edit=hasPermission(user.role,"document.update")&&!doc.archived_at,upload=edit&&hasPermission(user.role,"document.upload"),archive=hasPermission(user.role,"document.delete");
 const person=(id:string|null)=>o.profiles.find(x=>x.id===id);const personName=(id:string|null)=>{const p=person(id);return p?[p.first_name,p.last_name].filter(Boolean).join(" ")||id:id||"—";};
 return <><Link href="/documenti">Archivio documenti</Link><div className="d-flex justify-content-between gap-3 my-3"><h1 className="h3">{doc.title||doc.original_filename}</h1><div className="d-flex gap-2">{edit&&<Link className="btn btn-outline-secondary" href={`/documenti/${id}/edit`}>Modifica metadata</Link>}{upload&&<Link className="btn btn-dark" href={`/documenti/${id}/versions/new`}>Nuova versione</Link>}</div></div>{p.success&&<p className="alert alert-success">{p.success}</p>}
 <div className="app-card p-3 mb-3"><dl className="row mb-0">{[
 ['Categoria',[doc.category_code,doc.category_name].filter(Boolean).join(' — ')],['Stato',documentStatusLabels[doc.display_status]],['Società SIMI',doc.entity_name],['Numero / riferimento',doc.reference],['Data documento',doc.document_date],['Scadenza',doc.expiry_date],['Paese / lingua',[doc.country,doc.language].filter(Boolean).join(' / ')],['Descrizione',doc.description],['Note',doc.notes],['Responsabile',personName(doc.assigned_to)],['Caricato da',personName(doc.created_by)],['Caricamento',doc.created_at],['Ultima modifica',doc.updated_at],['Visibilità',({general:'Standard',restricted:'Riservato',hr:'HR'} as Record<string,string>)[doc.access_scope]],['Dipendente',doc.employee_id],['Nome originale corrente',doc.original_filename],['Nome normalizzato corrente',doc.normalized_filename],['Nome Storage corrente',doc.stored_filename],['Percorso Storage corrente',doc.storage_path],
 ].map(([label,value])=><div className="row mb-2" key={label}><dt className="col-md-3">{label}</dt><dd className="col-md-9 mb-0 text-break">{value||'—'}</dd></div>)}</dl></div>
 <div className="app-card p-3 mb-3"><h2 className="h5">Collegamenti</h2><div className="d-flex flex-wrap gap-3">{doc.projects.map(x=><Link key={x.id} href={`/commesse/${x.id}`}>Commessa {x.label}</Link>)}{doc.companies.map(x=><Link key={x.id} href={`/${x.type==='supplier'?'fornitori':'clienti'}/${x.id}`}>{x.label}</Link>)}{doc.invoices.map(x=><Link key={x.id} href={`/fatture/${x.id}`}>Fattura {x.label}</Link>)}{doc.expiry_date&&<Link href={`/scadenze?kind=document&q=${encodeURIComponent(doc.title||doc.original_filename)}`}>Scadenziario</Link>}</div>{edit&&<details className="mt-3"><summary>Aggiungi collegamenti</summary><form action={linkDocumentAction} className="row g-3 mt-1"><input name="id" type="hidden" value={id}/><ContextFields options={o}/><div><SubmitButton className="btn btn-outline-secondary" pendingLabel="Collegamento…">Collega senza duplicare il file</SubmitButton></div></form></details>}</div>
 <div className="app-card p-3 mb-3"><h2 className="h5">Versione corrente — {doc.version_number}</h2>{doc.file_state==='ready'&&!doc.archived_at?<><a className="btn btn-outline-secondary mb-3" href={`/documenti/versioni/${doc.current_version_id}/file?download=1`}><i className="bi bi-download me-2"/>Scarica</a><iframe title={doc.title||doc.original_filename} src={`/documenti/versioni/${doc.current_version_id}/file`} width="100%" height="600"/></>:<p className="text-muted">{doc.archived_at?'Documento archiviato. Ripristinalo per accedere ai file.':doc.file_state==='failed'?'Upload fallito. Carica una nuova versione.':'Upload in attesa di finalizzazione.'}</p>}</div>
 <h2 className="h5">Tutte le versioni</h2><div className="table-responsive"><table className="table table-sm"><thead><tr>{['Versione','File originale / normalizzato','Data / autore','Hash SHA-256','Note','Azioni'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{versions.map(v=><tr key={v.id}><td>{v.version_number} {v.label}{v.id===doc.current_version_id&&<span className="badge text-bg-primary ms-1">Corrente</span>}<div className="small text-muted">{v.file_state}</div></td><td>{v.original_filename}<div className="small text-muted">{v.normalized_filename||'Nome normalizzato non presente sul file legacy'}</div></td><td>{v.created_at}<div>{personName(v.created_by)}</div></td><td className="small text-break" style={{maxWidth:190}}>{v.content_hash||'Non calcolato sul file legacy'}</td><td>{v.notes||'—'}</td><td>{v.file_state==='ready'&&!doc.archived_at&&<><a href={`/documenti/versioni/${v.id}/file`} target="_blank" rel="noreferrer">Apri</a> · <a href={`/documenti/versioni/${v.id}/file?download=1`}>Scarica</a></>}{v.file_state==='pending'&&upload&&v.created_by===user.id&&<form action={finalizeDocumentAction}><input type="hidden" name="id" value={id}/><input type="hidden" name="version" value={v.id}/><label className="form-check small"><input className="form-check-input" type="checkbox" name="acknowledge_duplicate" value="1"/>Conferma eventuale contenuto duplicato</label><SubmitButton className="btn btn-sm btn-outline-secondary" pendingLabel="Finalizzazione…">Riprova finalizzazione</SubmitButton></form>}</td></tr>)}</tbody></table></div>
 <div className="app-card p-3 my-3"><h2 className="h5">Eventi registrati</h2>{!events.length?<p className="text-muted">Nessun evento disponibile.</p>:<table className="table table-sm"><thead><tr><th>Data</th><th>Utente</th><th>Azione</th><th>Oggetto</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{e.created_at}</td><td>{personName(e.user_id)}</td><td>{e.action}</td><td>{e.entity_type}</td></tr>)}</tbody></table>}<p className="small text-muted">Ultimi 100 eventi disponibili.</p></div>
 {archive&&<form action={doc.archived_at?restoreDocumentAction:deleteDocumentAction}><input type="hidden" name="id" value={id}/><ConfirmSubmitButton confirmMessage={doc.archived_at?'Ripristinare questo documento?':'Archiviare il documento conservando tutte le versioni?'}>{doc.archived_at?'Ripristina documento':'Archivia documento'}</ConfirmSubmitButton></form>}
 </>;
}
