import { ProjectCycle } from "@/components/commercial/project-cycle";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePagePermission, getAccessScope, authorizedClient } from "@/lib/permissions";
import { getProjectById, getProjectSummary, getProjectActivity, getInvoices, getProfileDirectory } from "@/lib/data";
import { getDeadlines } from "@/lib/deadlines";
import { ContextDocuments } from "@/components/documents/context-documents";
import { ActivityTimeline } from "@/components/ui/activity-timeline";
import { ConfirmSubmitButton } from "@/components/ui/confirm-submit-button";
import { deleteProjectAction } from "@/lib/crud";
import { hasPermission } from "@/lib/auth";
import { checkDatabase } from "@/lib/errors";
import { ProjectOffersContracts } from "@/components/commercial/project-offers-contracts";

const labels:Record<string,string>={draft:"Preparazione",active:"Attiva",suspended:"Sospesa",completed:"Completata",closed:"Chiusa",archived:"Archiviata"};
function money(value:number,currency:string){return value.toLocaleString("it-IT",{style:"currency",currency});}
export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  await requirePagePermission("project.read"); const id=(await params).id; const project=await getProjectById(id); if(!project)notFound(); const access=await getAccessScope("project");
  const [summary,invoices,deadlines,events,profiles]=await Promise.all([getProjectSummary(id),getInvoices({project_id:id}),getDeadlines({project:id},false),getProjectActivity(id),getProfileDirectory()]);
  const names=new Map(profiles.map(p=>[p.id,[p.first_name,p.last_name].filter(Boolean).join(" ")||"Utente"]));
  const timeline=events.map(e=>({time:new Date(e.created_at).toLocaleString("it-IT"),user:e.user_id?names.get(e.user_id)||"Utente":"Sistema",title:`${e.entity_type} · ${e.action}`,description:`Evento registrato sulla commessa ${project.project_code}.`}));
  const db=await authorizedClient("project.read"); const cat=await db.rpc("project_document_categories",{project:id}); checkDatabase(cat.error); const categories=(cat.data??[]) as {id:string;code:string;name:string;items:number}[]; const lineResult=invoices.length?await db.from("invoice_lines").select("invoice_id,amount_total").eq("project_id",id).in("invoice_id",invoices.map(x=>x.id)):({data:[],error:null}); checkDatabase(lineResult.error); const attributed=new Map<string,number>(); for(const row of lineResult.data??[])attributed.set(String(row.invoice_id),(attributed.get(String(row.invoice_id))??0)+Number(row.amount_total));
  const canDeadline=access.role?hasPermission(access.role,"deadline.write"):false;
  return <>
    <div className="d-flex justify-content-between align-items-center gap-3 mb-3 flex-wrap"><div><Link href="/commesse" className="small">← Commesse</Link><h1 className="h3 mb-0">{project.project_code} — {project.name}</h1></div><div className="d-flex gap-2">{access.canUpdate&&<Link className="btn btn-outline-secondary" href={`/commesse/${id}/edit`}><i className="bi bi-pencil me-2"/>Modifica</Link>}{access.canUpload&&<Link className="btn btn-primary" href={`/documenti/new?project=${id}`}><i className="bi bi-upload me-2"/>Carica documento</Link>}{access.canCreate&&<Link className="btn btn-outline-primary" href={`/fatture/new?project=${id}`}>Nuova fattura</Link>}{canDeadline&&<Link className="btn btn-outline-primary" href={`/scadenze/new?project=${id}&entity=${project.legal_entity_id||""}`}>Nuova scadenza</Link>}{access.canDelete&&<form action={async()=>{"use server";await deleteProjectAction(id);}}><ConfirmSubmitButton confirmMessage={`Archiviare la commessa ${project.project_code}?`}>Archivia</ConfirmSubmitButton></form>}</div></div>
    <div className="app-card p-3 mb-3"><dl className="row mb-0"><dt className="col-md-3">Società SIMI</dt><dd className="col-md-3">{project.entity_name||"—"}</dd><dt className="col-md-3">Cliente</dt><dd className="col-md-3">{project.customer_id?<Link href={`/clienti/${project.customer_id}`}>{project.customer_name}</Link>:"—"}</dd><dt className="col-md-3">Responsabile</dt><dd className="col-md-3">{project.project_manager_name||"—"}</dd><dt className="col-md-3">Stato</dt><dd className="col-md-3"><span className="badge text-bg-secondary">{labels[project.status]||project.status}</span></dd><dt className="col-md-3">Luogo</dt><dd className="col-md-3">{[project.city,project.country].filter(Boolean).join(", ")||"—"}</dd><dt className="col-md-3">Apertura</dt><dd className="col-md-3">{project.opening_date||"—"}</dd><dt className="col-md-3">Inizio previsto</dt><dd className="col-md-3">{project.planned_start_date||"—"}</dd><dt className="col-md-3">Fine prevista</dt><dd className="col-md-3">{project.expected_closing_date||"—"}</dd><dt className="col-md-3">Descrizione</dt><dd className="col-md-9">{project.description||"—"}</dd><dt className="col-md-3">Note</dt><dd className="col-md-9">{project.notes||"—"}</dd></dl></div>
    <div className="row g-3 mb-3">{[["Documenti",summary.documents,"/documenti?project="+id],["Fatture",summary.invoices,"#fatture"],["Fatture fornitori",summary.supplier_invoices,"#fatture"],["Fatture clienti",summary.customer_invoices,"#fatture"],["Scadenze aperte",summary.open_deadlines,"/scadenze?project="+id],["Scadenze scadute",summary.overdue_deadlines,"/scadenze?project="+id+"&period=overdue"]].map(([label,value,href])=><div className="col-6 col-lg-2" key={String(label)}><Link href={String(href)} className="app-card p-3 d-block text-decoration-none h-100"><div className="small text-muted">{label}</div><div className="fs-4 fw-semibold">{value}</div></Link></div>)}</div>
    {summary.financial.length>0&&<div className="app-card p-3 mb-3"><h2 className="h5">Residui finanziari per valuta</h2><div className="table-responsive"><table className="table table-sm"><thead><tr><th>Tipo</th><th>Valuta</th><th>Attribuito</th><th>Saldato</th><th>Residuo</th></tr></thead><tbody>{summary.financial.map((x,i)=><tr key={i}><td>{x.kind==="payment"?"Da pagare":"Da incassare"}</td><td>{x.currency}</td><td>{money(x.original,x.currency)}</td><td>{money(x.settled,x.currency)}</td><td>{money(x.residual,x.currency)}</td></tr>)}</tbody></table></div></div>}
    <div id="fatture" className="app-card p-3 mb-3"><h2 className="h5">Fatture collegate</h2><div className="table-responsive"><table className="table table-sm align-middle"><thead><tr><th>Tipo</th><th>Numero</th><th>Data</th><th>Controparte</th><th>Totale</th><th>Quota commessa</th><th>Stato</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.invoice_type==="purchase"?"Fornitore":"Cliente"}</td><td><Link href={`/fatture/${i.id}`}>{i.invoice_number}</Link></td><td>{i.invoice_date||"—"}</td><td>{i.customer_name||"—"}</td><td>{money(i.amount_total,i.currency)}</td><td>{attributed.has(i.id)?money(attributed.get(i.id)!,i.currency):"Non determinabile"}</td><td>{i.status}</td></tr>)}{!invoices.length&&<tr><td colSpan={7} className="text-muted">Nessuna fattura collegata.</td></tr>}</tbody></table></div></div>
    <ProjectCycle id={id}/><ProjectOffersContracts id={id}/><div className="row g-3"><div className="col-lg-7"><ContextDocuments project={id} entity={project.legal_entity_id}/><div className="app-card p-3 mb-3"><h2 className="h5">Categorie documentali SIMI</h2><div className="d-flex flex-wrap gap-2">{categories.map(c=><Link key={c.id} className="btn btn-sm btn-outline-secondary" href={`/documenti?project=${id}&category=${c.id}`}>{c.code} {c.name} <span className="badge text-bg-secondary">{c.items}</span></Link>)}</div></div><div className="app-card p-3"><h2 className="h5">Scadenze collegate</h2>{deadlines.rows.slice(0,50).map(d=><div key={d.id} className="d-flex justify-content-between border-bottom py-2"><Link href={d.invoice_id?`/fatture/${d.invoice_id}`:`/scadenze/${d.id.replace("manual:","")}`}>{d.title}</Link><span>{d.due_date} · {d.temporal_status}</span></div>)}{!deadlines.rows.length&&<p className="text-muted mb-0">Nessuna scadenza collegata.</p>}</div></div><div className="col-lg-5"><ActivityTimeline items={timeline}/></div></div>
  </>;
}
