import { FilterForm } from "@/components/ui/filter-form";
import { FilterToolbar } from "@/components/ui/filter-toolbar";
import { RowActionsMenu } from "@/components/ui/row-actions-menu";
import { StatusBadge } from "@/components/ui/status-badge";
import { formatDate, formatMoney } from "@/lib/formatters";
import Link from "@/components/ui/app-link";
import { SubmitButton } from "@/components/ui/submit-button";
import { ConfirmSubmitButton } from "@/components/ui/confirm-submit-button";
import { getAccessScope, requirePagePermission } from "@/lib/permissions";
import { getFinancialMovements, getMovementReferences } from "@/lib/finance";
import { getLegalEntities, getAllCompanies } from "@/lib/data";
import { saveFinancialMovementAction,archiveFinancialMovementAction } from "@/lib/crud";

export default async function FinancePage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
  await requirePagePermission("invoice.read");
  const access=await getAccessScope("invoice");
  const params=await searchParams;
  const [movements, entities, companies] = await Promise.all([getFinancialMovements(), getLegalEntities(), getAllCompanies()]);
  const references=await getMovementReferences(movements.flatMap(m=>m.allocations??[]));
  const editing=access.canUpdate?movements.find(m=>m.id===params.edit):undefined;
  const filteredMovements = movements.filter(m => {
    const allocated=(m.allocations??[]).reduce((sum:number,a:{amount:number})=>sum+Number(a.amount),0);
    const status=allocated<=0?"unallocated":allocated<Number(m.amount)?"partially_allocated":"allocated";
    const query=params.q?.trim().toLocaleLowerCase("it");
    return (!params.movement || m.id===params.movement) && (!query || [m.reference,m.counterparty?.business_name,...(m.allocations??[]).map((a:{invoice_id:string})=>references.invoices.get(a.invoice_id))].some(v=>v?.toLocaleLowerCase("it").includes(query))) && (!params.direction||m.direction===params.direction) && (!params.status||status===params.status) && (!params.entity||m.legal_entity_id===params.entity) && (!params.company||m.counterparty_id===params.company) && (!params.from||m.movement_date>=params.from) && (!params.to||m.movement_date<=params.to);
  });
  return <><div className="d-flex flex-wrap gap-3 justify-content-between align-items-center mb-4"><div><h1 className="h3">Pagamenti e incassi</h1><p className="text-muted mb-0">Movimenti reali e allocazioni sulle fatture.</p></div>{access.canUpdate&&<Link href="/pagamenti#movimento" className="btn btn-primary"><i className="bi bi-plus-lg me-2"/>Nuovo movimento</Link>}</div>
    {access.canUpdate&&<div id="movimento" className="app-card p-3 mb-4"><h2 className="h5">{editing?"Modifica movimento":"Nuovo movimento"}</h2><form key={editing?.id??"new"} action={saveFinancialMovementAction} className="row g-2"><input type="hidden" name="id" value={editing?.id??""}/><input type="hidden" name="account_id" value={editing?.account_id??""}/>
      <div className="col-md-2"><label className="form-label small">Tipo</label><select name="direction" defaultValue={editing?.direction??"payment"} className="form-select"><option value="payment">Pagamento</option><option value="receipt">Incasso</option></select></div>
      <div className="col-md-2"><label className="form-label small">Data</label><input name="movement_date" defaultValue={editing?.movement_date??new Date().toISOString().slice(0,10)} type="date" className="form-control" required /></div>
      <div className="col-md-2"><label className="form-label small">Importo</label><input name="amount" defaultValue={editing?.amount??""} type="number" min="0.01" step="0.01" className="form-control" required /></div>
      <div className="col-md-2"><label className="form-label small">Valuta</label><input name="currency" defaultValue={editing?.currency??"EUR"} maxLength={3} className="form-control" required /></div>
      <div className="col-md-4"><label className="form-label small">Società SIMI</label><select name="legal_entity_id" defaultValue={editing?.legal_entity_id??""} className="form-select" required><option value="">Seleziona…</option>{entities.map(e=><option key={e.id} value={e.id}>{e.business_name}</option>)}</select></div>
      <div className="col-md-4"><label className="form-label small">Controparte</label><select name="counterparty_id" defaultValue={editing?.counterparty_id??""} className="form-select"><option value="">Non specificata</option>{companies.map(c=><option key={c.id} value={c.id}>{c.business_name}</option>)}</select></div>
      <div className="col-md-3"><label className="form-label small">Metodo</label><input name="payment_method" defaultValue={editing?.payment_method??""} className="form-control" /></div><div className="col-md-3"><label className="form-label small">Riferimento</label><input name="reference" defaultValue={editing?.reference??""} className="form-control" /></div>
      <input type="hidden" name="allocations_json" value={JSON.stringify(editing?.allocations??[])} /><div className="col-12"><label className="form-label small">Note</label><input name="notes" defaultValue={editing?.notes??""} className="form-control" /></div><div className="col-12"><SubmitButton className="btn btn-primary" pendingLabel="Salvataggio…">{editing?"Salva modifiche":"Registra movimento"}</SubmitButton>{editing&&<Link className="btn btn-outline-secondary ms-2" href="/pagamenti">Annulla modifica</Link>}</div>
    </form></div>}
    <FilterForm>{params.edit&&<input type="hidden" name="edit" value={params.edit}/>}<FilterToolbar activeCount={[params.entity,params.company,params.from,params.to].filter(Boolean).length} advanced={<>
<div className="col-md-3"><label className="form-label" htmlFor="filter-entity">Società</label><select id="filter-entity" name="entity" defaultValue={params.entity||""} className="form-select"><option value="">Tutte</option>{entities.map(e=><option key={e.id} value={e.id}>{e.business_name}</option>)}</select></div>
<div className="col-md-3"><label className="form-label" htmlFor="filter-company">Soggetto</label><select id="filter-company" name="company" defaultValue={params.company||""} className="form-select"><option value="">Tutti</option>{companies.map(c=><option key={c.id} value={c.id}>{c.business_name}</option>)}</select></div>
{[["from","Dal"],["to","Al"]].map(([name,label])=><div className="col-md-3" key={name}><label className="form-label" htmlFor={`filter-${name}`}>{label}</label><input id={`filter-${name}`} type="date" name={name} defaultValue={params[name]} className="form-control"/></div>)}</>}>
<div><label className="form-label" htmlFor="filter-q">Ricerca</label><input id="filter-q" name="q" defaultValue={params.q} className="form-control" placeholder="Soggetto, riferimento, fattura"/></div>
<div><label className="form-label" htmlFor="filter-direction">Tipo</label><select id="filter-direction" name="direction" defaultValue={params.direction||""} className="form-select"><option value="">Tutti</option><option value="payment">Pagamenti</option><option value="receipt">Incassi</option></select></div>
<div><label className="form-label" htmlFor="filter-status">Stato</label><select id="filter-status" name="status" defaultValue={params.status||""} className="form-select"><option value="">Tutti</option><option value="unallocated">Da allocare</option><option value="partially_allocated">Parziale</option><option value="allocated">Allocato</option></select></div>
</FilterToolbar></FilterForm><div className="app-card"><div className="table-responsive"><table className="table table-admin align-middle"><thead><tr><th>Data</th><th>Tipo</th><th>Soggetto</th><th>Riferimento</th><th className="col-money">Importo</th><th>Stato</th><th className="col-actions"><span className="visually-hidden">Azioni</span></th></tr></thead><tbody>{filteredMovements.length===0&&<tr><td colSpan={7} className="empty-state">Nessun movimento registrato.</td></tr>}{filteredMovements.map(m=>{const allocated=(m.allocations??[]).reduce((s:number,a:{amount:number})=>s+Number(a.amount),0);return <tr key={m.id}><td className="col-date">{formatDate(m.movement_date)}</td><td className="col-status"><i className={`bi ${m.direction==="payment"?"bi-arrow-up-right":"bi-arrow-down-left"} me-1`} aria-hidden="true"/>{m.direction === "payment" ? "Pagamento" : "Incasso"}</td><td className="col-description" title={m.counterparty?.business_name}>{m.counterparty?.business_name??"—"}<div className="small text-muted text-truncate" title={m.entity?.business_name}>{m.entity?.business_name}</div></td><td className="col-description" title={m.reference??undefined}>{m.reference&&<div className="text-truncate">{m.reference}</div>}{(m.allocations??[]).map((a:{invoice_id:string;installment_id:string|null},index:number)=><Link key={index} className="d-block text-truncate" href={`/fatture/${a.invoice_id}`}>{references.invoices.get(a.invoice_id)||"Fattura collegata"}{a.installment_id&&<> · Rata {references.installments.get(a.installment_id)||"collegata"}</>}</Link>)}{!m.reference&&!m.allocations?.length&&"—"}</td><td className="col-money">{formatMoney(m.amount,m.currency)}</td><td className="col-status"><StatusBadge domain="payment" status={allocated<=0?"unallocated":allocated<Number(m.amount)?"partially_allocated":"allocated"}/><div className="small text-muted">{allocated>0&&allocated<Number(m.amount)?`${formatMoney(allocated,m.currency)} allocati`:null}</div></td><td className="col-actions">{(access.canUpdate||access.canDelete)&&<RowActionsMenu label={`Azioni movimento ${m.reference||formatDate(m.movement_date)}`}>{access.canUpdate&&<Link className="dropdown-item" href={`/pagamenti?edit=${m.id}#movimento`}>Modifica</Link>}{access.canDelete&&<form action={async()=>{"use server";await archiveFinancialMovementAction(m.id);}}><ConfirmSubmitButton confirmMessage="Archiviare il movimento e ricalcolare i residui delle fatture?">Archivia</ConfirmSubmitButton></form>}</RowActionsMenu>}</td></tr>})}</tbody></table></div></div></>;
}
