import Link from "next/link";
import { SubmitButton } from "@/components/ui/submit-button";
import { ConfirmSubmitButton } from "@/components/ui/confirm-submit-button";
import { getAccessScope, requirePagePermission } from "@/lib/permissions";
import { getFinancialMovements } from "@/lib/finance";
import { getLegalEntities, getAllCompanies } from "@/lib/data";
import { saveFinancialMovementAction,archiveFinancialMovementAction } from "@/lib/crud";

export default async function FinancePage({searchParams}:{searchParams:Promise<{edit?:string}>}) {
  await requirePagePermission("invoice.read");
  const access=await getAccessScope("invoice");
  const params=await searchParams;
  const [movements, entities, companies] = await Promise.all([getFinancialMovements(), getLegalEntities(), getAllCompanies()]);
  const editing=access.canUpdate?movements.find(m=>m.id===params.edit):undefined;
  return <><div className="d-flex justify-content-between align-items-center mb-4"><div><h1 className="h3">Pagamenti e incassi</h1><p className="text-muted mb-0">Movimenti reali e allocazioni sulle fatture.</p></div>{access.canUpdate&&<Link href="/pagamenti#movimento" className="btn btn-primary"><i className="bi bi-plus-lg me-2"/>Nuovo movimento</Link>}</div>
    {access.canUpdate&&<div id="movimento" className="app-card p-3 mb-4"><h2 className="h5">{editing?"Modifica movimento":"Nuovo movimento"}</h2><form key={editing?.id??"new"} action={saveFinancialMovementAction} className="row g-2"><input type="hidden" name="id" value={editing?.id??""}/><input type="hidden" name="account_id" value={editing?.account_id??""}/>
      <div className="col-md-2"><label className="form-label small">Tipo</label><select name="direction" defaultValue={editing?.direction??"payment"} className="form-select"><option value="payment">Pagamento</option><option value="receipt">Incasso</option></select></div>
      <div className="col-md-2"><label className="form-label small">Data</label><input name="movement_date" defaultValue={editing?.movement_date??new Date().toISOString().slice(0,10)} type="date" className="form-control" required /></div>
      <div className="col-md-2"><label className="form-label small">Importo</label><input name="amount" defaultValue={editing?.amount??""} type="number" min="0.01" step="0.01" className="form-control" required /></div>
      <div className="col-md-2"><label className="form-label small">Valuta</label><input name="currency" defaultValue={editing?.currency??"EUR"} maxLength={3} className="form-control" required /></div>
      <div className="col-md-4"><label className="form-label small">Società SIMI</label><select name="legal_entity_id" defaultValue={editing?.legal_entity_id??""} className="form-select" required><option value="">Seleziona…</option>{entities.map(e=><option key={e.id} value={e.id}>{e.business_name}</option>)}</select></div>
      <div className="col-md-4"><label className="form-label small">Controparte</label><select name="counterparty_id" defaultValue={editing?.counterparty_id??""} className="form-select"><option value="">Non specificata</option>{companies.map(c=><option key={c.id} value={c.id}>{c.business_name}</option>)}</select></div>
      <div className="col-md-3"><label className="form-label small">Metodo</label><input name="payment_method" defaultValue={editing?.payment_method??""} className="form-control" /></div><div className="col-md-3"><label className="form-label small">Riferimento</label><input name="reference" defaultValue={editing?.reference??""} className="form-control" /></div>
      <input type="hidden" name="allocations_json" value={JSON.stringify(editing?.allocations??[])} /><div className="col-12"><label className="form-label small">Note</label><input name="notes" defaultValue={editing?.notes??""} className="form-control" /></div><div className="col-12"><SubmitButton className="btn btn-primary" pendingLabel="Salvataggio…">{editing?"Salva modifiche":"Registra movimento"}</SubmitButton>{editing&&<Link className="btn btn-outline-secondary ms-2" href="/pagamenti">Annulla modifica</Link>}</div>
    </form></div>}
    <div className="app-card p-3"><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Data</th><th>Tipo</th><th>Società</th><th>Controparte</th><th>Importo</th><th>Metodo</th><th>Riferimento</th><th>Allocato</th><th>Non allocato</th><th>Azioni</th></tr></thead><tbody>{movements.length===0&&<tr><td colSpan={10} className="text-muted">Nessun movimento registrato.</td></tr>}{movements.map(m=>{const allocated=(m.allocations??[]).reduce((s:number,a:{amount:number})=>s+Number(a.amount),0);return <tr key={m.id}><td>{m.movement_date}</td><td>{m.direction === "payment" ? "Pagamento" : "Incasso"}</td><td>{m.entity?.business_name ?? "—"}</td><td>{m.counterparty?.business_name ?? "—"}</td><td>{Number(m.amount).toLocaleString("it-IT",{style:"currency",currency:m.currency})}</td><td>{m.payment_method??"—"}</td><td>{m.reference??"—"}</td><td>{allocated.toFixed(2)} {m.currency}</td><td>{Math.max(0,Number(m.amount)-allocated).toFixed(2)} {m.currency}</td><td><div className="d-flex gap-2">{access.canUpdate&&<Link className="btn btn-sm btn-outline-secondary" href={`/pagamenti?edit=${m.id}#movimento`}>Modifica</Link>}{access.canDelete&&<form action={async()=>{"use server";await archiveFinancialMovementAction(m.id);}}><ConfirmSubmitButton confirmMessage="Archiviare il movimento e ricalcolare i residui delle fatture?">Archivia</ConfirmSubmitButton></form>}</div>{(m.allocations??[]).map((a:{invoice_id:string},index:number)=><Link key={index} className="d-block small" href={`/fatture/${a.invoice_id}`}>Fattura collegata</Link>)}</td></tr>})}</tbody></table></div></div></>;
}
