import Link from "@/components/ui/app-link";
import { StatusBadge } from "@/components/ui/status-badge";
import { RowActionsMenu } from "@/components/ui/row-actions-menu";
import { formatDate } from "@/lib/formatters";
import { sourceLabels, type Task, type Anomaly, type LinkedRecord, type WorkFilters } from "@/lib/work/model";
export function RecordLink({record}:{record:LinkedRecord|null}){return record?<Link href={record.href}>{sourceLabels[record.kind]} · {record.label}</Link>:<span>—</span>;}
export function WorkTabs({base,p,views}:{base:string;p:WorkFilters;views:[string,string][]}){return <nav className="nav nav-pills gap-1 mb-3" aria-label="Viste rapide">{views.map(([value,label])=>{const q=new URLSearchParams(Object.entries(p).filter(([k,v])=>v!==undefined&&k!=="page"&&k!=="view") as [string,string][]);q.set("view",value);return <Link key={value} className={`nav-link py-1${(p.view??views[0][0])===value?" active":""}`} href={`${base}?${q}`}>{label}</Link>;})}</nav>;}
export function WorkPagination({count,page,p}:{count:number;page:number;p:WorkFilters}){const url=(n:number)=>{const q=new URLSearchParams(Object.entries(p).filter(([,v])=>v!==undefined) as [string,string][]);q.set("page",String(n));return `?${q}`;};return <nav aria-label="Paginazione" className="d-flex gap-3 mt-3">{page>1&&<Link href={url(page-1)}>Precedente</Link>}<span>{count} risultati · Pagina {page}</span>{page*50<count&&<Link href={url(page+1)}>Successiva</Link>}</nav>;}
export function TaskTable({rows,names,entities}:{rows:Task[];names:Map<string,string>;entities:Map<string,string>}){return <div className="table-responsive"><table className="table table-admin align-middle"><thead><tr><th>Attività</th><th>Collegata a</th><th>Responsabile</th><th>Scadenza</th><th>Priorità</th><th>Stato</th><th className="col-actions"><span className="visually-hidden">Azioni</span></th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td className="col-description"><Link href={`/attivita/${t.id}`}>{t.title}</Link><div className="small text-muted">{entities.get(t.legal_entity_id)}</div></td><td className="col-description">{t.links.slice(0,2).map(l=><div key={`${l.kind}:${l.id}`}><RecordLink record={l}/></div>)}{t.links.length>2&&<small>+{t.links.length-2} collegamenti</small>}{t.anomaly_id&&<Link href={`/anomalie/${t.anomaly_id}`} className="small">Anomalia</Link>}</td><td>{t.assigned_to?names.get(t.assigned_to)||"Utente":"—"}</td><td className="col-date">{formatDate(t.due_date)}</td><td className="col-status"><StatusBadge domain="priority" status={t.priority}/></td><td className="col-status"><StatusBadge domain="task" status={t.status}/></td><td className="col-actions"><RowActionsMenu><Link href={`/attivita/${t.id}`} className="dropdown-item">Apri attività</Link></RowActionsMenu></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="text-muted">Nessuna attività corrisponde ai filtri.</td></tr>}</tbody></table></div>;}
export function AnomalyTable({rows,names,canCreate}:{rows:Anomaly[];names:Map<string,string>;canCreate:boolean}){return <div className="table-responsive"><table className="table table-admin align-middle"><thead><tr><th>Anomalia</th><th>Record</th><th>Rilevata</th><th>Responsabile</th><th>Severità</th><th>Stato</th><th className="col-actions"><span className="visually-hidden">Azioni</span></th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td className="col-description"><Link href={`/anomalie/${a.id}`}>{a.title}</Link></td><td className="col-description"><RecordLink record={a.link}/></td><td className="col-date">{formatDate(a.detected_at)}</td><td>{a.assigned_to?names.get(a.assigned_to)||"Utente":"—"}</td><td className="col-status"><StatusBadge domain="severity" status={a.severity}/></td><td className="col-status"><StatusBadge domain="anomaly" status={a.status}/></td><td className="col-actions"><RowActionsMenu><Link className="dropdown-item" href={`/anomalie/${a.id}`}>Apri anomalia</Link>{canCreate&&<Link className="dropdown-item" href={`/attivita/new?anomaly=${a.id}`}>Crea attività</Link>}</RowActionsMenu></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="text-muted">Nessuna anomalia corrisponde ai filtri.</td></tr>}</tbody></table></div>;}
